### ISSUE TITLE
ヘッダーのリンク

### ISSUE THREAD

**Issue by k-suzuki-k** [gworks-github/naganoenbando#125]
ユーザ側には商品一覧があった方がよさそうじゃないですか？

管理者側のロゴのリンクですが、
ログインしていないと管理者画面入れないようにしているので、
ログイン画面でロゴ押すとエラーになります。
ログイン・登録画面ではロゴのリンクを外すか、
そもそもロゴにはリンクを外す方がよいかもです。

**Comment by kottu55** [comment]
かしこまりました、対応します！

**Comment by kottu55** [comment]
対応完了しました。確認できましたらクローズお願いします。
