### ISSUE TITLE
ランキング機能について

### ISSUE THREAD

**Issue by k-suzuki-k** [gworks-github/naganoenbando#38]
~~先週分(例:11/4～11/10)のいいね数ランキングを
今週一週間(例:11/11～11/17)の間に表示させると思います。~~

~~先週分のいいねの合計数の保持の仕方や
いいねを削除した際のランキングの影響を確認中ですが、
実装に時間が掛かりそうです。~~

---

集計期間:1週間
例 今日が11/17の場合
集計期間 11/10～11/16

---

メンターさんアドバイス
-  上位10位くらいなら画面表示の影響は少ない
-  集計対象のいいねが取り消されてランキングが変わるのも問題ない

⇒明日11/18までには機能実装します

---
**参考URL**
https://qiita.com/nekojoker/items/0e65509837550c140938
https://qiita.com/MitsuguSueyoshi/items/18fa5e49a27e727f00b4

**先週一週間分の日付の出し方**
~~irb(main):014:0> 1.week.ago.beginning_of_week
=> Mon, 04 Nov 2019 00:00:00 UTC +00:00
irb(main):015:0> 1.week.ago.end_of_week
=> Sun, 10 Nov 2019 23:59:59 UTC +00:00
irb(main):016:0>~~

irb(main):017:0> 1.week.ago.beginning_of_day
=> Sun, 10 Nov 2019 00:00:00 UTC +00:00
irb(main):018:0> 1.day.ago.end_of_day
=> Sat, 16 Nov 2019 23:59:59 UTC +00:00
irb(main):019:0>

集計
Item.find(Like.where(created_at:1.week.ago.beginning_of_day..1.day.ago.end_of_day).group(:item_id).order(Arel.sql('count(item_id) desc')).limit(5).pluck(:item_id))

**Comment by k-suzuki-k** [comment]
明日11/18までには機能実装します

**Comment by kottu55** [comment]
対応ありがとうございます。

**Comment by k-suzuki-k** [comment]
確認完了後のいいね数の非表示や集計日数の変更があるので、
忘れないようにCloseはまだしないようにお願いします。
