### ISSUE TITLE
Itemモデルのbelogs_toがコメントアウトされている件

### ISSUE THREAD

**Issue by k-suzuki-k** [gworks-github/naganoenbando#41]
Itemモデルのbelogs_toがコメントアウトされてますが、
外してもいいねですよね？？

https://github.com/gworks-github/naganoenbando/blob/49cd804265b47873609f75cb9f76251c83919c70/app/models/item.rb#L7-L9

コメントアウト削除後のリレーション確認済み
irb(main):016:0> item.artist
=> #<Artist id: 1, name: "Caravaggio", created_at: "2019-11-17 10:09:07", updated_at: "2019-11-17 10:09:07">
irb(main):017:0> item.genre
=> #<Genre id: 1, name: "Rap", created_at: "2019-11-17 10:09:07", updated_at: "2019-11-17 10:09:07">
irb(main):018:0> item.label
=> #<Label id: 1, name: "Fish and Chips", created_at: "2019-11-17 10:09:07", updated_at: "2019-11-17 10:09:07">
irb(main):019:0>

**Comment by kottu55** [comment]
すみません、OKです！

**Comment by k-suzuki-k** [comment]
プルリクしましたー
