### ISSUE TITLE
税率の固定値について

### ISSUE THREAD

**Issue by mizu19961203** [gworks-github/naganoenbando#63]
情報マスタでの税率変更機能作成の際、<%= Tax.find(item.tax_id).rate %> で
税率が呼び出せませんでした。

価格表示はワイヤーフレーム通りと決まりましたが、現在の税率に初期値を合わせるためには、
seedsで設定されている　tax_id  = 1 を　tax_id  = 10　と変更すれば良いのでしょうか。

**Comment by k-suzuki-k** [comment]
rateは登録しましたか？
