### ISSUE TITLE
【エラー】入荷予定に入れた商品を削除した場合

### ISSUE THREAD

**Issue by kottu55** [gworks-github/naganoenbando#77]
入荷予定に入れた商品を削除した場合、入荷予定一覧が見れなくなります。
修正の優先順位はかなり低いと思います。

**Comment by kottu55** [comment]
入荷済商品一覧も同様。

商品を削除した場合、そのIDの入荷予定商品と入荷済み商品のレコードを消す。

**Comment by k-suzuki-k** [comment]
has_many～deoend: :destoryが漏れているっぽいです。見直します。
