### ISSUE TITLE
情報マスタがadmin配下になっていない

### ISSUE THREAD

**Issue by kottu55** [gworks-github/naganoenbando#79]

**Comment by k-suzuki-k** [comment]
route.rbを「管理者用」に直すだけでなくて、
info_controllerやviewをadmin配下に作る必要がありますね。

あとアプリケーション詳細設計だとURLが「/admin/info_master」になってました。

https://github.com/gworks-github/naganoenbando/blob/686ca3e505ba2ac7e12d7ddf1a7617fefb85a5ec/config/routes.rb#L60-L75
