### ISSUE TITLE
ユーザー　商品詳細画面について

### ISSUE THREAD

**Issue by mizu19961203** [gworks-github/naganoenbando#92]
・track no, が表示されません。seedsでコメントアウトしているが原因でしょうか。
・いいねボタンでの　”いいねしていない”という文言は、編集できますか？

**Comment by k-suzuki-k** [comment]
・track no, が表示されません。seedsでコメントアウトしているが原因でしょうか。
全商品ですか？

・いいねボタンでの　”いいねしていない”という文言は、編集できますか？
機能実装の段階で一時的にわかりやすい文言やレイアウトに変えているだけなので、
気付いた点あったら適宜ワイヤーフレームに沿って修正してもらえると助かります。
